Container test - run:servers
jatitoam/joomla-testing pull request #1
Opened 2017-04-22 14:18 UTC by isacandrei

I have sun three tests in a row by running the commands 

- run:servers
- run:tests
- docker rm -f client
- stop:servers

It seems like the error I had with the client container had something to do with my testing environment.
Please check if it works for you too.

2017-04-24 01:01 UTC, jatitoam requested changes
Just a small comment and a question

2017-04-24 01:01 UTC, jatitoam commented on RoboFile.php
> +				'5901' => '5900'
I recall doing this change but still having the problem, so it works for you, right?

2017-04-24 01:01 UTC, jatitoam commented on RoboFile.php
> +//		$dockerTesting->set('daemon', false);
Can you please clean this up? Thanks

2017-04-24 01:02 UTC, jatitoam commented
check this out https://github.com/joomla-projects/joomla-testing/commit/cd820d132bc6e5c60ee1df372254b38ecca6456e

2017-04-24 01:02 UTC, jatitoam commented
it seems this repo (my own) is just outdated

2017-04-24 08:05 UTC, isacandrei commented on RoboFile.php
> +				'5901' => '5900'
Yes, it is mapped correctly now. I successfully connected to VNC.

2017-04-24 08:11 UTC, isacandrei commented
I have done the cleanup. I will make the full request on the main repository also.

2017-04-24 19:47 UTC, jatitoam commented
Actually that's my point, if you see the main repository it's updated like you just did (I forgot to make the change in my fork)

2018-07-28 15:05 UTC, closed without merging

2018-08-09 22:31 UTC, jatitoam commented
Heya @isacandrei  :)
It seems I missed this one but iirc it went directly to the upstream fork?